apiVersion: v1
kind: Secret
metadata:
  name: image-pull-secret
data:
  .dockerconfigjson: ewogICJhdXRocyI6IHsKICAgICJyZWctZGhjLmFwcC5jb3JwaW50cmEubmV0IjogewogICAgICAiYXV0aCI6ICJTMEZOUlZKQlR6cFVWSFpPU0dsU1RtcFlVM2hhS3pkTlN6bHBWVVJGY201cmRsaElZM1J5YTNSaVNsZGxNMnBWUlVObWRrcEpkWGRNUlVsNWQzUlBjVmt3ZGxkUVlYWnQiLAogICAgICAiZW1haWwiOiAiIgogICAgfQogIH0KfQ==
type: kubernetes.io/dockerconfigjson